baseURL: "https://naomi.unaids.org/news"
languageCode: "en-gb"
title: "Naomi News"
theme: ["papermod-changelog", "PaperMod"]
enableEmoji: true

params:
  # https://github.com/adityatelange/hugo-PaperMod/wiki/Installation#sample-configyml
  DateFormat: "1 Jan 2006"
  disableThemeToggle: true
  defaultTheme: light
  disableSpecial1stPost: true
  hideMeta: false
  ShowPostNavLinks: true
  homeInfoParams:
    Title: Naomi News Site
    Content: What's new and updated in the Naomi UI and model
  tags:
    - text: Update
      colour: "#FFBA11"
    - text: Feature
      colour: "#14CC80"
    - text: Model
      colour: "#E31837"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
